name: Install cargo binaries
description: Install cargo binaries using cargo-binstall
inputs:
  binstall:
    description: "Programs to install with binstall"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install cargo bins
      shell: bash
      run: >
        cargo-binstall --no-confirm --min-tls-version 1.3 --force ${{ inputs.binstall }}
